/*
 文件说明:
   更新 env_alarm_settings、env_device_settings 表数据
 前提条件:
   本机已安装并正常运行 PostgreSQL 服务，目标库中已存在对应表结构
 执行方式:
   psql -h <host> -p <port> -U <user> -d <dbname> -f pg_update.sql
   或在 pgAdmin Query Tool 中打开本文件后执行
 脚本做了什么:
   1. 清空 env_alarm_settings / env_device_settings 表数据
   2. 重新插入 两个表中的最新基础数据
   3. 重置两表 id 序列到当前最大 id
   4. 将 sys_job 中「实时表分表」「历史表分表」任务的 status 更新为 1

 Date: 27/07/2026
*/

BEGIN;

SET search_path TO public;

-- =============================================
-- 1. env_alarm_settings
-- =============================================
DELETE FROM "public"."env_alarm_settings";

INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (1, '13', '{"id":1,"device_info":{"logicdevice_station.filter_changer.o3":["branch_temp"],"logicdevice_station.filter_changer.co":["branch_temp"],"logicdevice_station.filter_changer.nox":["branch_temp"],"logicdevice_station.filter_changer.so2":["branch_temp"]},"name":"支管冷凝水预警","description":"当露点温度高于设备间温度时，给出预示并建议空调设定值","icon":"Cloud","category":"sampling","enabled":true,"configurable":true,"configs":[{"label":"支管温度校准量","type":"number","value":1,"min":-10,"max":10,"step":0.1,"class":"coefficient"},{"label":"","type":"setting","dew_point_device_id":"logicdevice.meteo","dew_point_param_id":"dew_point"}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:48:12', '2026-06-05 11:27:58.085', 73);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (2, '10', '{"id":2,"device_info":{"logicdevice_station.paper_tape.pm10":["remaining_spots"],"logicdevice_station.paper_tape.pm25":["remaining_spots"]},"name":"颗粒物纸带更换","description":"当纸带剩余量低于阈值，给出更换预警提示","icon":"HardDrive","category":"equipment","enabled":true,"configurable":true,"configs":[{"label":"剩余量阈值 (%)","type":"number","value":70,"min":0,"max":100,"step":1},{"label":"","type":"setting","logicdevice_station.paper_tape.pm10":"total_spots","logicdevice_station.paper_tape.pm25":"total_spots"}]}', 'admin', 'admin', '2025-05-26 13:47:40', '2026-03-18 16:42:24.878', 140);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (3, '14', '{"id":72,"device_info":{"logicdevice.nox":["alarm_status"],"logicdevice.so2":["alarm_status"],"logicdevice.co":["alarm_status"],"logicdevice.o3":["alarm_status"],"logicdevice_station.calibrator":["alarm_status"],"logicdevice.pm25":["alarm_status"],"logicdevice.pm10":["alarm_status"]},"name":"监测设备报警","description":"当各个监测设备出现报警时触发","icon":"Settings","category":"equipment","enabled":true,"configurable":false}', 'admin', 'admin', '2025-05-26 13:48:20', '2025-06-12 16:37:20.758', 80);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (4, '8', '{"id":4,"device_info":{"logicdevice_station.indoor_pollutant":["so2_indoor","o3_indoor","no2_indoor","co_indoor"]},"name":"标准气体泄漏","description":"当检测到标气泄露，超出阈值范围，启动报警并自动开启排风扇","icon":"Wind","category":"gas","enabled":true,"configurable":true,"configs":[{"label":"站房 CO 浓度阈值（PPM）","type":"number","value":0.5,"min":-10,"max":1000,"step":1,"class":"co_concentration"},{"label":"站房 NO2 浓度阈值（PPM）","type":"number","value":0.5,"min":-10,"max":1000,"step":1,"class":"no2_concentration"},{"label":"站房 SO2 浓度阈值（PPM）","type":"number","value":0.5,"min":-10,"max":1000,"step":1,"class":"so2_concentration"},{"label":"","type":"setting","device_id":"logicdevice_station.exhaust_fan","param_id":"speed"}]}', 'admin', 'admin', '2025-05-26 13:47:19', '2026-03-19 09:11:33.757', 120);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (5, '9', '{"id":5,"device_info":{"logicdevice_station.standard_gas.co":["gas_pressure_remaining"],"logicdevice_station.standard_gas.so2":["gas_pressure_remaining"],"logicdevice_station.standard_gas.nox":["gas_pressure_remaining"]},"name":"标准气体更换","description":"当标准气体剩余量低于阈值范围，给出更换预警提示","icon":"Battery","category":"gas","enabled":true,"configurable":true,"configs":[{"label":"SO2 钢瓶气压力阈值（kPa）","type":"number","value":0,"min":0,"max":100000,"step":1,"class":"co"},{"label":"NOX 钢瓶气压力阈值（kPa）","type":"number","value":0,"min":0,"max":100000,"step":1,"class":"so2"},{"label":"CO 钢瓶气压力阈值（kPa）","type":"number","value":0,"min":0,"max":100000,"step":1,"class":"nox"}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:47:29', '2026-06-04 17:44:07.063', 130);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (6, '17', '{"id":138,"device_info":{"logicdevice_station.camera.1":["intrusion_alarm"],"logicdevice_station.camera.2":["intrusion_alarm"],"logicdevice_station.camera.3":["intrusion_alarm"],"logicdevice_station.camera.4":["intrusion_alarm"]},"name":"异常进入报警","description":"当有人进入站房区域，给出报警提示","icon":"User","category":"security","enabled":true,"configurable":false}', 'admin', 'admin', '2025-05-26 13:48:44', '2025-06-04 12:01:08.268', 180);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (7, '4', '{"id":7,"device_info":{"logicdevice_station.power_meter":["voltage_a","voltage_b","voltage_c"]},"name":"供电电源异常波动","description":"当供电电源的电压超过设定范围，且持续时间超过设定时间，触发报警","icon":"Bolt","category":"power","enabled":true,"configurable":true,"configs":[{"label":"电压范围 (V)","type":"range","value":[198,242],"min":150,"max":300,"step":1},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'admin', '2025-05-26 13:46:23', '2026-02-04 10:07:34.019', 40);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (8, '3', '{"id":67,"device_info":{"logicdevice_station.security_alarm":["water_leak"]},"name":"设备间漏水","description":"当设备间任一采样口位置发生漏水，水浸传感器触发报警","icon":"Droplet","category":"environment","enabled":true,"configurable":false}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:46:10', '2026-06-04 17:38:53.21', 30);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (9, '12', '{"id":9,"device_info":{"logicdevice_station.sampling_tube":["temperature"]},"name":"采样总管温度异常","description":"当采样总管内样气温度超出阈值范围，且持续时间超过设定时间，触发报警","icon":"Thermometer","category":"sampling","enabled":true,"configurable":true,"configs":[{"label":"温度范围 (℃)","type":"range","value":[30,40],"min":-20,"max":60,"step":1},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:48:03', '2026-06-05 10:16:09.862', 70);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (10, '2', '{"id":10,"device_info":{"logicdevice_station.th":["humidity"]},"name":"设备间湿度异常","description":"当设备间的湿度传感器测量值超出阈值范围，且持续时间超过设定时间，触发报警","icon":{"name":"Warning","__name":"warning"},"category":"environment","enabled":true,"configurable":true,"configs":[{"label":"湿度范围 (%)","type":"range","value":[30,80],"min":0,"max":100,"step":1},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:45:50', '2026-06-04 17:55:50.361', 20);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (11, '5', '{"id":11,"device_info":{"logicdevice_station.ups":["input_voltage"]},"name":"稳压电源异常波动","description":"当稳压电源的电压超过设定范围，且持续时间超过设定时间，触发报警","icon":"Gauge","category":"power","enabled":true,"configurable":true,"configs":[{"label":"电压范围 (V)","type":"range","value":[198,242],"min":150,"max":300,"step":1},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:46:35', '2026-06-04 17:51:48.819', 41);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (12, '16', '{"id":73,"device_info":{"logicdevice_station.security_alarm":["smoke_1","smoke_2"]},"name":"消防报警","description":"当站房发生火情时，烟感报警装置启动报警并主动切断供电电源","icon":"Flame","category":"security","enabled":true,"configurable":true,"configs":[{"label":"","type":"setting","device_id":"logicdevice_station.voltage_regulator","param_id":"relay_ch2"}]}
', 'admin', 'admin', '2025-05-26 13:48:37', '2025-07-08 11:34:26.558', 90);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (13, '11', '{"id":13,"device_info":{"logicdevice_station.sampling_tube":["retention_time"]},"name":"采样总管流速异常","description":"当采样总管内样气的滞留时间大于设定值，且持续时间超过设定时间，触发报警","icon":"Fan","category":"sampling","enabled":true,"configurable":true,"configs":[{"label":"滞留时间 (s)","type":"number","value":2,"min":0,"max":60,"step":1,"class":"retention"},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:47:53', '2026-06-05 11:09:45.893', 71);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (14, '15', '{"id":137,"device_info":{"logicdevice_station.ups":["input_voltage"]},"name":"断电和恢复报警","description":"当监测场地发生断电特殊情况，给出断电报警提示；电源恢复后，给出来电恢复报警提示","icon":"Power","category":"security","enabled":true,"configurable":false}', 'admin', 'admin', '2025-05-26 13:48:29', '2025-06-04 12:01:00.519', 170);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (15, '1', '{"id":15,"device_info":{"logicdevice_station.th":["temperature"]},"name":"设备间温度异常","description":"当设备间的温度传感器测量值超出阈值范围，且持续时间超过设定时间，触发报警","icon":"Thermometer","category":"environment","enabled":true,"configurable":true,"configs":[{"label":"温度范围 (℃)","type":"range","value":[20,30],"min":-20,"max":60,"step":1},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:39:44', '2026-06-04 17:55:48.072', 10);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (16, '18', '{"id":74,"device_info":{"logicdevice_station.camera.1":["interference_alarm"],"logicdevice_station.camera.2":["interference_alarm"],"logicdevice_station.camera.3":["interference_alarm"],"logicdevice_station.camera.4":["interference_alarm"]},"name":"干扰报警","description":"自动识别雾炮喷淋等站房周边人为干扰行为，并给出报警提示","icon":"EyeOff","category":"security","enabled":true,"configurable":false}', 'admin', 'admin', '2025-05-26 13:48:51', '2025-05-26 17:03:57.441', 100);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (17, '6', '{"id":17,"device_info":{"logicdevice_station.power_meter":["current_a","current_b","current_c"]},"name":"电流异常波动","description":"当供电电流突然升高或降低，超出阈值范围，且持续时间超过设定时间，触发报警","icon":"Zap","category":"power","enabled":true,"configurable":true,"configs":[{"label":"电流范围 (A)","type":"range","value":[0,10],"min":0,"max":30,"step":0.1},{"label":"持续时间","type":"duration","value":5,"min":1,"max":60,"step":1}]}', 'admin', 'Admin7s9k2G5', '2025-05-26 13:46:51', '2026-06-04 18:00:44.014', 50);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (19, '23', '{"id":19,"device_info":{"logicdevice_station.indoor_pollutant":["pm10_indoor","pm25_indoor"]},"name":"站房洁净度报警","description":"站房洁净度报警，根据站房颗粒物来判断","icon":"Battery","category":"gas","enabled":true,"configurable":true,"configs":[{"label":"PM10报警阈值","type":"number","value":30,"min":0,"max":100000,"step":0.01,"class":"pm10_indoor"},{"label":"PM2.5报警阈值","type":"number","value":20,"min":0,"max":100000,"step":0.01,"class":"pm25_indoor"}]}', 'admin', 'admin', '2025-11-11 16:07:59', '2026-03-19 09:11:41.367', 200);
INSERT INTO "public"."env_alarm_settings" ("id", "alarm_type", "setting_content", "created_by", "updated_by", "create_time", "update_time", "sort") VALUES (20, '22', '{"id":139,"device_info":{"sms-qc":["infrared_status"]},"name":"门禁报警","description":"当非法人员使用门禁时触发报警！","icon":"User","category":"security","enabled":true,"configurable":false}', 'admin', 'admin', '2026-06-05 06:32:28.186255', '2026-06-05 06:32:28.186255', 220);

-- 重置 env_alarm_settings 序列
SELECT setval(pg_get_serial_sequence('public.env_alarm_settings', 'id'), COALESCE((SELECT MAX(id) FROM "public"."env_alarm_settings"), 1), true);

-- =============================================
-- 2. env_device_settings
-- =============================================
DELETE FROM "public"."env_device_settings";

INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (2, '门禁', '0', 50, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.access_control","logoType":"door","onlineAttributeId":"lock_status","commandList":[{"commandName":"门禁控制","attributeId":"door_control","displayType":"command_stateless"},{"commandName":"当前门锁状态","attributeId":"lock_status","displayType":"value"}]}', 'logicdevice_station.access_control', 'admin', 'Admin7s9k2G5', '2025-05-27 09:16:08', '2026-05-27 10:30:01.768');
INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (6, '空调01', '0', 10, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.air_conditioner.ac1","logoType":"air-conditioner","online":true,"onlineAttributeId":"power_status","commandList":[{"commandName":"温度调节","attributeId":"setpoint_temp","displayType":"value_change","valueUtil":"℃","changeType":"int","changeStep":1,"changeNumberMax":30,"changeNumberMin":16,"changeNumberDecimal":1},{"commandName":"电源","attributeId":"power_status","displayType":"command"},{"commandName":"风机转速","attributeId":"fan_speed","displayType":"command"},{"commandName":"运行模式","attributeId":"running_mode","displayType":"command"}]}', 'logicdevice_station.air_conditioner.ac1', 'admin', 'admin', '2025-05-27 09:06:05', '2025-11-03 16:45:20.435');
INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (7, '空调02', '0', 20, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.air_conditioner.ac2","logoType":"air-conditioner","online":true,"onlineAttributeId":"power_status","commandList":[{"commandName":"温度调节","attributeId":"setpoint_temp","displayType":"value_change","valueUtil":"℃","changeType":"int","changeStep":1,"changeNumberMax":30,"changeNumberMin":16,"changeNumberDecimal":1},{"commandName":"电源","attributeId":"power_status","displayType":"command"},{"commandName":"风机转速","attributeId":"fan_speed","displayType":"command"},{"commandName":"运行模式","attributeId":"running_mode","displayType":"command"}]}', 'logicdevice_station.air_conditioner.ac2', 'admin', 'admin', '2025-05-27 09:08:06', '2025-11-03 16:45:38.93');
INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (3, '室内灯光', '0', 30, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.lighting","logoType":"light","onlineAttributeId":"switch_status","commandList":[{"commandName":"电源","attributeId":"switch_status","displayType":"command"}]}', 'logicdevice_station.lighting', 'admin', 'admin', '2025-05-27 09:09:21', '2025-11-03 16:45:52.869');
INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (4, '排风扇', '0', 40, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.exhaust_fan","logoType":"fan","onlineAttributeId":"speed","commandList":[{"commandName":"电源","attributeId":"speed","displayType":"command"}]}', 'logicdevice_station.exhaust_fan', 'admin', 'admin', '2025-05-27 09:13:31', '2025-11-03 16:46:19.95');
INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (5, '智能稳压电源', '0', 73, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.voltage_regulator","logoType":"power","onlineAttributeId":"relay_ch1","commandList":[{"commandName":"第一路继电器","attributeId":"relay_ch1","displayType":"command"},{"commandName":"第二路继电器","attributeId":"relay_ch2","displayType":"command"},{"commandName":"第三路继电器","attributeId":"relay_ch3","displayType":"command"},{"commandName":"第四路继电器","attributeId":"relay_ch4","displayType":"command"}]}', 'logicdevice_station.voltage_regulator', 'admin', 'admin', '2025-06-23 09:36:27', '2025-11-03 16:48:38.031');
INSERT INTO "public"."env_device_settings" ("id", "device_name", "device_type", "sort", "setting_content", "device_id", "created_by", "updated_by", "create_time", "update_time") VALUES (1, '智能采样管', '0', 60, '{"deviceType":"logicDevice","deviceId":"logicdevice_station.sampling_tube","logoType":"tube","onlineAttributeId":"heating_actual_temp","commandList":[{"commandName":"实时加热温度","attributeId":"heating_actual_temp","displayType":"value","valueUtil":"℃"},{"commandName":"加热温度调节","attributeId":"heating_set_temp","displayType":"value_change","valueUtil":"℃","changeType":"int","changeStep":5,"changeNumberMax":50,"changeNumberMin":30,"changeNumberDecimal":0}]}', 'logicdevice_station.sampling_tube', 'admin', 'admin', '2025-06-23 09:14:38', '2025-11-03 16:47:54.951');

-- 重置 env_device_settings 序列
SELECT setval(pg_get_serial_sequence('public.env_device_settings', 'id'), COALESCE((SELECT MAX(id) FROM "public"."env_device_settings"), 1), true);

-- =============================================
-- 3. sys_job：同步实时表/历史表分表任务 status
--    init 后,新pg需要关闭这两条分表任务 status 可能为 0 启用，统一更新为 1 关闭
--    init 后,质控报告生成时间调整到每日 00:05:00
-- =============================================
UPDATE "public"."sys_job"
SET "status" = '1',
    "update_time" = CURRENT_TIMESTAMP
WHERE "job_id" IN (11, 12)
   OR ("job_name" IN ('实时表分表', '历史表分表')
       AND "job_group" = 'CreatePartitionTablesTask');

UPDATE "public"."sys_job"
SET "cron_expression" = '0 5 0 * * ?',
    "update_time" = CURRENT_TIMESTAMP
WHERE "job_id" IN (15)
   OR ("job_name" IN ('质控报告定时自动生成')
    AND "job_group" = 'DEFAULT');

COMMIT;
